name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          
          # Stash any local changes
          git stash
          
          # Reset file permissions before pull
          sudo find . -type f -exec chmod 664 {} \;
          sudo find . -type d -exec chmod 775 {} \;
          
          # Nettoyer les dossiers problématiques
          sudo rm -rf vendor
          sudo rm -rf bootstrap/cache/*
          
          # Pull les derniers changements
          git pull
          
          # Installer les dépendances
          composer install --no-dev --optimize-autoloader
          
          # Corriger les permissions après installation
          sudo chown -R www-data:www-data .
          sudo chmod -R 775 storage bootstrap/cache vendor
          
          # Vider les caches d'abord
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          php artisan cache:clear
          
          # Puis recréer les caches
          php artisan config:cache
          php artisan route:cache
          
          # Migrations
          php artisan migrate --force